TKE -  POOL JAN-FEV/2021
noesis-br/tkefev2021 pull request #1
Opened 2021-02-23 15:40 UTC by ClaudioRegal

questões 05 e 06, utilize o site http://automationpractice.com/index.php
5 - Criar uma conta de usuário. O campo zip postal requer 5 dígitos (ex.: 38601)
6 - Logar com o usuário criado e comprar Blouse (qtd 2) e printed Summer dress. Validar compra.

2021-02-23 15:43 UTC, ClaudioRegal commented
Aplicadas boas práticas boas práticas como: legibilidade, reusabilidade, encapsulamentos utilizados e Manutenibilidade.

2021-02-23 19:01 UTC, uLucasFraga requested changes
@ClaudioRegal acredito que você tenha esquecido de anexar os drivers dentro da pasta.

2021-02-23 19:01 UTC, uLucasFraga commented on tke/RESPOSTAS_TKE.md
> +Já um projeto pequeno, com funcionalidades simples e que tenham pouco tempo de desenvolvimento, não tem necessidade de automação.
acredito que qualquer projeto, independente do seu tamanho, a automação será bem vinda.

inclusive, vejo que o diferencial está em conseguir ter o "**feeling**" de não querer automatizar/tentar cobrir todos os cenários manuais.

por isso, com a quantidade de cenários comumente aumentando a cada semana, o ideal é sabermos que vale mais termos um conjunto de testes funcionando e que batam no **core da aplicação**, do que termos milhões de testes automatizados que não validam o necessário.

então, dependendo do contexto seria:
- automatizar as áreas que são mais importantes em uma perpectiva do negócio.
- automatizar features que não possam ficar offline nunca (login, compra e etc...)
- automatizar features que são propensas a quebras e comumente instáveis.

o resto, pode ser evitável.

2021-03-01 16:46 UTC, uLucasFraga approved these changes

2021-03-01 16:46 UTC, merged